name: "Build Docker Image"
description: |
  "Build das imagens do Backend e Frontend"

inputs:
  registry_name:
    description: "Docker Registry"
    required: true
  docker_login:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true
  project_name:
    description: "Project Name"
    required: true
  dockerfile_name:
    description: "Dockerfile Name"
    required: true
  git_branch:
    description: "Branch"
    default: ${{ github.ref_name }}
  build:
    description: "Github build number"
    default: ${{ github.run_number }}
  tag:
    description: "Tag da imagem. Default: latest"
    default: ${{ github.ref_name }}

runs:
  using: "composite"
  steps:
    - name: Extract tag last number
      shell: bash
      run: |
          echo "$GITHUB_REF_NAME"
          EXTRACT_LAST_NUMBER=$(echo "$GITHUB_REF_NAME" | sed 's/.*\.//')
          echo "EXTRACT_LAST_NUMBER=$EXTRACT_LAST_NUMBER" >> $GITHUB_ENV
          echo "Extract: $EXTRACT_LAST_NUMBER"

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.6.0

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ inputs.registry_name }}
        username: ${{ inputs.docker_login }}
        password: ${{ inputs.docker_password }}
        logout: true

    - name: Build and push Docker
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ${{ inputs.dockerfile_name }}
        build-args: |
          BUILD=${{ inputs.build }}
          RELEASE=${{ env.EXTRACT_LAST_NUMBER }}
        labels: |
          --label source-branch=${{ github.ref_name }}
          --label build-commit=${{ github.sha }}
          --label repository=${{ github.repository }}
          --label source-build=github
        tags: |
          ${{ inputs.registry_name }}/${{ inputs.project_name }}:${{ inputs.tag }}
        push: true